name: Checn New Version

on:
  schedule:
    - cron: "8 0 */2 * *"   # <=== Change this value

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install PyGitHub
    - name: Check updates
      run: python update_xfs_deps.py
